const KEY="boardflow-v2";const board=new Date(Date.UTC(2027,1,15));
const base={tab:"home",available:150,exams:[],routine:[["06:00–06:20","Ready"],["06:30–14:20","School"],["14:20–14:50","Lunch + shower"],["15:00–17:00","Coaching"],["17:30–18:00","Rest"],["18:00–23:00","Study + dinner + school work"],["23:00","Sleep"]],subjects:[
["Maths",12,0,"NCERT • Oswaal • PYQs • tests"],["Science",13,0,"NCERT • concepts • Oswaal • PYQs"],["SST",22,0,"NCERT • Oswaal • maps • PYQs"],["English",12,0,"Literature • writing • grammar"],["Hindi",10,0,"Literature • writing • grammar"]],tasks:[
[1,"Maths — current chapter practice","Maths",45,3,false],[2,"Science — NCERT + active recall","Science",40,3,false],[3,"SST — one chapter + questions","SST",40,2,false],[4,"English/Hindi — literature or writing","English/Hindi",30,1,false],[5,"Board PYQs — timed practice","Boards",35,2,false]]};
let s=load();function load(){try{return {...base,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return structuredClone(base)}}function save(){localStorage.setItem(KEY,JSON.stringify(s))}
const $=q=>document.querySelector(q);const esc=x=>String(x).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));function daysLeft(){let n=new Date();return Math.max(0,Math.ceil((board-new Date(n.getFullYear(),n.getMonth(),n.getDate()))/86400000))}function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1500)}
function plan(){let a=Math.max(0,+s.available||0),now=new Date(),items=[];s.exams.filter(e=>new Date(e.date+"T00:00:00")>=new Date(now.getFullYear(),now.getMonth(),now.getDate())).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,3).forEach(e=>{let d=Math.ceil((new Date(e.date+"T00:00:00")-now)/86400000);e.portion.split(/,|\n/).map(x=>x.trim()).filter(Boolean).slice(0,3).forEach(p=>items.push({t:e.name+" — "+p,m:35,r:"exam in "+d+" day"+(d==1?"":"s"),score:100-Math.min(70,d*2)}))});s.tasks.filter(t=>!t[5]).forEach(t=>items.push({t:t[1],m:t[3],r:"backlog • priority "+t[4],score:t[4]*18}));items.push({t:"Board PYQs — timed practice",m:35,r:"keep board prep active",score:34});items.sort((a,b)=>b.score-a.score);let used=0,out=[];for(let x of items)if(used+x.m<=a){out.push(x);used+=x.m}return out}
function render(){let tab=s.tab,n=new Date(),h=n.getHours(),g=h<12?"Good morning.":h<17?"Keep moving.":"Lock in.";let done=s.tasks.filter(t=>t[5]).length,p=Math.round(done/s.tasks.length*100);let pages={home:`<section class="hero"><div><div class="eyebrow">${n.toLocaleDateString(undefined,{weekday:"long",day:"numeric",month:"short"})}</div><h1>${g}</h1><div class="muted">Your day changes. Your plan changes with it.</div></div><div class="count"><strong>${daysLeft()}</strong><span>DAYS TO BOARDS</span></div></section><div class="grid3"><div class="stat"><span>AVAILABLE</span><b>${Math.floor(s.available/60)}h ${s.available%60}m</b><small>today</small></div><div class="stat"><span>PROGRESS</span><b>${p}%</b><small>tasks complete</small></div><div class="stat"><span>BACKLOG</span><b>${s.tasks.length-done}</b><small>open tasks</small></div></div><section class="card focus"><div class="cardhead"><div><div class="eyebrow">SMART MODE</div><h2>What should I study now?</h2></div><button class="primary" id="build">Build plan</button></div><div id="homeplan">${planHTML()}</div></section><section class="card"><div class="cardhead"><div><div class="eyebrow">TODAY</div><h2>How much time do you have?</h2></div><button class="secondary" id="timebtn">Change</button></div><div class="muted">${s.available} minutes • planner will fit tasks into this window.</div></section><section class="card"><div class="cardhead"><div><div class="eyebrow">UP NEXT</div><h2>School exams</h2></div><button class="secondary" id="add">+ Add</button></div>${examsHTML(2)}</section>`,
plan:`<section class="hero"><div><div class="eyebrow">ADAPTIVE PLANNER</div><h1>Today's plan</h1><div class="muted">Highest priority first. No guilt spiral.</div></div></section><section class="card"><div class="cardhead"><div><div class="eyebrow">AVAILABLE</div><h2>${s.available} minutes</h2></div><button class="secondary" id="timebtn">Change</button></div>${planHTML()}</section><section class="card"><div class="cardhead"><div><div class="eyebrow">RECOVERY</div><h2>Open tasks</h2></div></div>${tasksHTML()}</section>`,
exams:`<section class="hero"><div><div class="eyebrow">EXAM CENTER</div><h1>Exams</h1><div class="muted">Add the date and exact portion. BoardFlow handles urgency.</div></div><button class="primary" id="add">+ Add exam</button></section><section class="card">${examsHTML()}</section>`,
subjects:`<section class="hero"><div><div class="eyebrow">BOARD ROADMAP</div><h1>Subjects</h1><div class="muted">Track syllabus progress and keep every subject alive.</div></div></section><section class="card">${subjectsHTML()}</section>`,
progress:`<section class="hero"><div><div class="eyebrow">PROGRESS</div><h1>${p}% complete</h1><div class="muted">Progress is based on completed planner tasks.</div></div></section><section class="card"><div class="cardhead"><div><div class="eyebrow">TASKS</div><h2>${done} / ${s.tasks.length}</h2></div></div><div class="progressbar"><div class="fill" style="width:${p}%"></div></div></section><section class="card"><div class="cardhead"><div><div class="eyebrow">SUBJECT SNAPSHOT</div><h2>Roadmap</h2></div></div>${subjectsHTML()}</section>`,
settings:`<section class="hero"><div><div class="eyebrow">CONTROL CENTER</div><h1>Settings</h1><div class="muted">Make BoardFlow fit your real life.</div></div></section><section class="card">${settingsHTML()}</section>`};$("#app").innerHTML=pages[tab];document.querySelectorAll("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));bind()}
function planHTML(){let x=plan();if(!x.length)return '<div class="empty">No task fits this time window. Try adding 30 more minutes.</div>';let used=x.reduce((a,b)=>a+b.m,0);return x.map((p,i)=>`<div class="planitem"><span class="num">${i+1} • ${p.m}m</span><div><b>${esc(p.t)}</b><small>${esc(p.r)}</small></div></div>`).join("")+`<div class="meta">Planned ${used} / ${s.available} minutes. Remaining time is your buffer.</div>`}
function examsHTML(limit){let a=[...s.exams].sort((x,y)=>x.date.localeCompare(y.date));if(limit)a=a.slice(0,limit);if(!a.length)return '<div class="empty">No school exams added yet.</div>';return a.map((e,i)=>{let d=Math.ceil((new Date(e.date+"T00:00:00")-new Date())/86400000);return `<div class="exam"><div class="examtop"><div class="examname">${esc(e.name)}</div><button class="iconbtn del" data-i="${i}">Delete</button></div><div class="meta">${new Date(e.date+"T00:00:00").toLocaleDateString()} • ${d>=0?d+" days left":"passed"}</div><div class="portion">${esc(e.portion)}</div></div>`}).join("")}
function subjectsHTML(){return s.subjects.map((x,i)=>{let pct=Math.round(x[2]/x[1]*100);return `<div class="subject"><div class="subjecttop"><span>${esc(x[0])}</span><span>${pct}%</span></div><div class="progressbar"><div class="fill" style="width:${pct}%"></div></div><div class="meta">${esc(x[3])}</div><div class="row" style="margin-top:8px"><button class="chip" data-sub="${i}" data-dir="-1">−</button><button class="chip" data-sub="${i}" data-dir="1">+ chapter done</button></div></div>`}).join("")}
function tasksHTML(){return s.tasks.map(t=>`<label class="task ${t[5]?"done":""}"><input type="checkbox" data-task="${t[0]}" ${t[5]?"checked":""}><span><b>${esc(t[1])}</b><span class="meta">${esc(t[2])} • ${t[3]} min • priority ${t[4]}</span></span></label>`).join("")}
function settingsHTML(){return `<div class="setting"><b>Board target</b><span>15 February 2027 • countdown is automatic.</span></div><div class="setting"><b>Available time today</b><span>Currently ${s.available} minutes.</span><div class="row" style="margin-top:8px"><button class="secondary" id="timebtn">Change time</button></div></div><div class="setting"><b>Routine</b><span>Edit your school, coaching, rest and study blocks.</span><div class="row" style="margin-top:8px"><button class="secondary" id="routinebtn">Edit routine</button></div></div><div class="setting"><b>Data</b><span>Your plan is stored locally on this device.</span><div class="row" style="margin-top:8px"><button class="secondary" id="reset">Reset app</button></div></div>`}
function bind(){let b=$("#build");if(b)b.onclick=()=>render();let add=$("#add");if(add)add.onclick=()=>{$("#modal").hidden=false;$("#ename").focus()};let tb=$("#timebtn");if(tb)tb.onclick=()=>{let v=prompt("How many minutes can you study today?",s.available);v=Math.max(0,Math.min(720,parseInt(v)||0));s.available=v;save();render();toast("Today's time updated")};document.querySelectorAll(".del").forEach(x=>x.onclick=()=>{let i=+x.dataset.i;s.exams.splice(i,1);save();render();toast("Exam deleted")});document.querySelectorAll("[data-task]").forEach(x=>x.onchange=()=>{let t=s.tasks.find(t=>t[0]==x.dataset.task);if(t)t[5]=x.checked;save();render()});document.querySelectorAll("[data-sub]").forEach(x=>x.onclick=()=>{let q=s.subjects[+x.dataset.sub];q[2]=Math.max(0,Math.min(q[1],q[2]+(+x.dataset.dir)));save();render()});let rb=$("#routinebtn");if(rb)rb.onclick=()=>{let v=prompt("One line per slot: time|activity",s.routine.map(x=>x.join("|")).join("\n"));if(v){s.routine=v.split("\n").map(x=>x.split("|").map(y=>y.trim())).filter(x=>x.length>1);save();toast("Routine saved")}};let reset=$("#reset");if(reset)reset.onclick=()=>{if(confirm("Reset all BoardFlow data?")){localStorage.removeItem(KEY);s=load();render();toast("Reset complete")}}}
document.querySelectorAll("#nav button").forEach(b=>b.onclick=()=>{s.tab=b.dataset.tab;save();render()});$("#close").onclick=()=>$("#modal").hidden=true;$("#examform").onsubmit=e=>{e.preventDefault();s.exams.push({name:$("#ename").value.trim(),date:$("#edate").value,portion:$("#eportion").value.trim()});save();$("#modal").hidden=true;e.target.reset();render();toast("Exam added")};
let deferred=null;addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;$("#install").hidden=false});$("#install").onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;$("#install").hidden=true}};if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{});render();